export const routes = [
  {
    id: "lux1",
    name: "Luxury Express",
    type: "AC Sleeper",
    from: "Mumbai",
    to: "Pune",
    departure: "08:30 PM",
    arrival: "01:45 AM",
    price: 850,
    rating: 4.8,
    amenities: ["Live Tracking", "Water Bottle", "Charging"],
    bookedSeats: ["1B", "2C", "4A"],
    source: "swiftbus",
  },
  {
    id: "gold2",
    name: "Rajdhani Travels",
    type: "AC Seater",
    from: "Delhi",
    to: "Jaipur",
    departure: "06:00 PM",
    arrival: "10:15 PM",
    price: 650,
    rating: 4.5,
    amenities: ["Charging", "Reading Light"],
    bookedSeats: ["1A", "3B", "5C"],
    source: "swiftbus",
  },
  {
    id: "green3",
    name: "Green Line",
    type: "Non-AC Seater",
    from: "Bengaluru",
    to: "Chennai",
    departure: "09:30 PM",
    arrival: "04:45 AM",
    price: 599,
    rating: 4.2,
    amenities: ["Live Tracking"],
    bookedSeats: ["2A", "6D"],
    source: "swiftbus",
  },
  {
    id: "swift4",
    name: "Swift Night Rider",
    type: "AC Sleeper",
    from: "Delhi",
    to: "Jaipur",
    departure: "10:00 PM",
    arrival: "03:00 AM",
    price: 730,
    rating: 4.1,
    amenities: ["Blanket", "Charging", "Snacks"],
    bookedSeats: ["7A", "7B", "7C"],
    source: "swiftbus",
  },
  {
    id: "swift5",
    name: "Swift Dawn",
    type: "AC Seater",
    from: "Delhi",
    to: "Jaipur",
    departure: "07:00 AM",
    arrival: "12:15 PM",
    price: 520,
    rating: 4.0,
    amenities: ["Charging"],
    bookedSeats: ["1C", "2B"],
    source: "swiftbus",
  },
];

export const thirdPartyRoutes = [
  {
    id: "rb101",
    provider: "redbus",
    name: "RedBus Starliner",
    type: "AC Seater",
    from: "Delhi",
    to: "Jaipur",
    departure: "05:30 PM",
    arrival: "10:00 PM",
    price: 610,
    rating: 4.2,
    amenities: ["Charging"],
    bookedSeats: ["3A", "3B"],
    source: "redbus",
  },
  {
    id: "zb202",
    provider: "zingbus",
    name: "ZingBus Prime",
    type: "AC Sleeper",
    from: "Delhi",
    to: "Jaipur",
    departure: "11:00 PM",
    arrival: "04:15 AM",
    price: 745,
    rating: 4.3,
    amenities: ["Blanket", "Charging"],
    bookedSeats: ["2D", "5A"],
    source: "zingbus",
  },
  {
    id: "rb303",
    provider: "redbus",
    name: "RedBus Comfort",
    type: "Non-AC Seater",
    from: "Mumbai",
    to: "Pune",
    departure: "09:00 PM",
    arrival: "12:40 AM",
    price: 480,
    rating: 4.0,
    amenities: ["Water Bottle"],
    bookedSeats: ["4C"],
    source: "redbus",
  },
];

export const offers = [
  {
    title: "Weekend Special",
    desc: "25% off on weekend bookings",
    code: "WEEKEND25",
    kind: "percent",
    value: 25,
  },
  {
    title: "First Trip Bonus",
    desc: "Save ₹100 on your first ride",
    code: "FIRST100",
    kind: "flat",
    value: 100,
  },
  {
    title: "Student Discount",
    desc: "Special price for students",
    code: "STUDENT15",
    kind: "percent",
    value: 15,
  },
];
